deployment:
  tasks:
    - export DEPLOYPATH=/home/rvz4kg30s062/repositories/LucidApparitionhub.io.git/public_html/
    - echo "$NEW_SSH_PRIVATE_KEY" > deploy_key.pem
    - chmod 600 deploy_key.pem
    - scp -o "HostKeyAlgorithms=ssh-rsa" -r -i deploy_key.pem ./build/* rvz4kg30s062@jeffgrafe.com:$DEPLOYPATH
  env:
    NODE_ENV: production
    NEW_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
