name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to cPanel
        run: |
          # Replace the placeholders with your cPanel SSH details and repository information
          echo "$DEPLOY_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          scp -r -i deploy_key.pem ./build/* rvz4kg30s062@jeffgrafe.com:/home/rvz4kg30s062/repositories/LucidApparitionhub.io.git/public_html/     
        env:
          NODE_ENV: production
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
