name: Deploy to Development

on:
  push:
    branches-ignore:
      - main
      - master
      - staging

jobs:
  deploy_development:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "Start time: $(date)"
          echo "Debug information"
          env
          echo "End time: $(date)"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_TOKEN}}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Set Git Identity
        run: |
          git config user.name "Jeff Grafe"
          git config user.email "jagrafe94@gmail.com"

      - name: Deploy to Development
        if: github.event_name == 'push'
        run: |
          if [ "$GITHUB_REF" == "refs/heads/development" ]; then
            if ! git show-ref --verify --quiet refs/heads/staging; then
              git checkout -b staging
            else
              git checkout staging
              git merge development --no-edit
          
              # Check if there are changes before pushing to the next branch
              if git diff --quiet; then
                echo "No changes to commit. Deployment to staging aborted."
              else
                git commit -am "Auto commit after successful deployment to Development"
                git push https://$GITHUB_ACTOR:$GH_TOKEN@github.com/LucidApparition/LucidApparition.github.io.git staging
              fi
            fi
          fi
