name: PR Generator

on:
  push:
    branches:
      - '*'

jobs:
  staging_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "Start time: $(date)"
          echo "Debug information"
          env
          echo "End time: $(date)"
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Check for specific conditions and label accordingly
        run: |
          changed_files=$(git --no-pager diff --name-only ${{ github.sha }})
          # Example: If the PR modifies a file in the "docs" folder, add a "Documentation" label
          if echo "$changed_files" | grep -q '^docs/'; then
            echo "Adding Documentation label"
            gh pr label add -l "Documentation"
          fi
          # Example: If the PR modifies a file in the "frontend" folder, add a "Frontend" label
          if echo "$changed_files" | grep -q '^frontend/'; then
            echo "Adding Frontend label"
            gh pr label add -l "Frontend"
          fi
          # You can add more conditions based on your project structure and requirements
          # Additional debugging output
          echo "Changed Files: $changed_files"
          echo "GitHub Ref: ${GITHUB_REF}"
          echo "GitHub SHA: ${GITHUB_SHA}"

      - name: Create Pull Request
        run: |
          response=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -d '{"title": "[Auto] Pull Request", "body": "Auto-generated pull request body", "head": "auto-pr-branch", "base": "master"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls")
  
          pr_url=$(echo "$response" | jq -r .html_url)
          echo "Pull Request created: $pr_url"