name: Auto-fill PR Description

on:
  pull_request:
    types: [opened]

jobs:
  auto_fill_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read PR template
        id: read_template
        run: |
          TEMPLATE_CONTENT=$(cat .github/prTemplate.md)
          echo "TEMPLATE<<EOF" >> $GITHUB_ENV
          echo "$TEMPLATE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Auto-fill PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r .pull_request.number "$GITHUB_EVENT_PATH")
          DESCRIPTION=$(grep -A 1000 "TEMPLATE" $GITHUB_ENV | tail -n +2)
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d "{\"body\": \"$DESCRIPTION\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
