name: PR Generator

on:
  push:
    branches:
      - '*'

jobs:
  staging_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "Start time: $(date)"
          echo "Debug information"
          env
          echo "End time: $(date)"

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Check for specific conditions and label accordingly
        run: |
          changed_files=$(git --no-pager diff --name-only ${{ github.sha }})

          # Example: If the PR modifies a file in the "docs" folder, add a "Documentation" label
          if echo "$changed_files" | grep -q '^docs/'; then
            echo "Adding Documentation label"
            gh pr label add -l "Documentation"
          fi

          # Example: If the PR modifies a file in the "frontend" folder, add a "Frontend" label
          if echo "$changed_files" | grep -q '^frontend/'; then
            echo "Adding Frontend label"
            gh pr label add -l "Frontend"
          fi

          # You can add more conditions based on your project structure and requirements

      - name: Size Label
        uses: pascalgn/size-label-action@v0.4.2
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Auto-generated pull request"
          title: "[Auto] Pull Request"
          body: |
            This pull request is automatically generated based on changes pushed to the repository.
          labels: "auto-generated"
          branch: "auto-pull-request-branch"
