name: Update Dependencies

on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  update-dep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update dependencies
        run: |
          npx -p npm-check-updates ncu -u
          npm install

      - name: Read PR Template
        id: read-template
        run: echo "::set-output name=pr_template::$(cat C:\Users\Jeff\Desktop\React-Portfolio\3d_portfolio\.github\prTemplate.md)"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: ${{ steps.read-template.outputs.pr_template }}
          branch: update-dependencies
